### ISSUE TITLE
Nightlies broken

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Make-Monaco-Builds#11]
I wonder if `npm install --save "typescript@next" --force` is not actually updating the typescript version - or  something was merged [14 days ago](https://github.com/microsoft/TypeScript/commits/main?after=e4fe50cca477a3e46f9b629a6c5be0b0ed8b010f+34&branch=main)

```
 - Creating release folder
> npm run release {"cwd":"monaco-editor"}
/home/runner/work/TypeScript-Make-Monaco-Builds/TypeScript-Make-Monaco-Builds/monaco-editor/node_modules/typescript/lib/typescript.js:7691
        var index = path.indexOf("\\");
                         ^
TypeError: path.indexOf is not a function
    at normalizeSlashes (/home/runner/work/TypeScript-Make-Monaco-Builds/TypeScript-Make-Monaco-Builds/monaco-editor/node_modules/typescript/lib/typescript.js:7691:26)
    at Object.combinePaths (/home/runner/work/TypeScript-Make-Monaco-Builds/TypeScript-Make-Monaco-Builds/monaco-editor/node_modules/typescript/lib/typescript.js:7757:28)
Command Failed:
STDOUT:
> @typescript-deploys/monaco-editor@4.7.0-dev.20220301 release
> ts-node ./build/build && ts-node ./build/release
```

**Comment by weswigham** [comment]
Something using nightly TS hasn't been updated to the new LS module resolver API shapes. We really should add an assertion saying it's a problem with something consuming TS.

**Comment by orta** [comment]
Hah, is it because I was leaving that both monaco and typescript made breaking changes in this release to make all this infra look fragile :P

Sounds like updating monaco-editor to 4.6 is probably the next step then. The tricky bit for me here is that the prod build builds and I don't easily have a way to provide either of the APIs at monaco level
